use_gpu: True
mode: 'train'
use_neptune: False

neptune_params:
    proj_name: 'ultimatejz/VRP-DQN-Simple'

env_params:
    map_dirc: './config/simple'
    n_bus: 2
    bus_capacity: 30
    bus_stop_time: 1
    skip_station: False
    frame_rate: 3
    total_time: 6

reward_params:
    queue_reward: -1
    wait_reward: 0
    opr_reward: 1000
    efficiency_reward: 0
    time_penalty_power: 1
    invalid_route_reward: -1000

agent_params:
    double_dqn: True
    batch_size: 32
    gamma: 0.99
    episodes: 2000
    loss: 'mse'
    fix_date: False
    replay_memory_cap: 100000
    replay_start: 0
    reward_verbose_freq: 200
    replay_freq: 1
    hist_len: 4
    target_update_freq: 5000
    epsilon:
        start: 0.3
        end: 0.001
        end_t: 2000
    optim_params:
        lr: 0.001
        momentum: 0.95
        eps: 0.01
    network:
        l1w: 512
        l2w: 256
        l3w: 256
    save_dir: './model_log/simple/'
    log_freq: 100