use_gpu: True
mode: 'train'
use_neptune: True

neptune_params:
    proj_name: 'ultimatejz/VRP-DQN'

env_params:
    map_dirc: './config/v1'
    n_bus: 10
    bus_capacity: 40
    bus_stop_time: 1
    skip_station: False
    frame_rate: 3
    total_time: 10

reward_params:
    queue_reward: -0.1
    wait_reward: 0
    opr_reward: 0
    efficiency_reward: 0
    time_penalty_power: 1
    invalid_route_reward: -100

agent_params:
    double_dqn: True
    batch_size: 32
    gamma: 0.99
    episodes: 400
    loss: 'mse'
    fix_date: False
    replay_memory_cap: 100000
    replay_start: 0
    reward_verbose_freq: 500
    replay_freq: 1
    hist_len: 4
    target_update_freq: 1000
    epsilon:
        start: 0.9
        end: 0.01
        end_t: 400
    optim_params:
        lr: 0.0001
        momentum: 0.95
        eps: 0.01
    save_dir: './tmp'