use_gpu: True
mode: 'train'
use_neptune: False

neptune_params:
    proj_name: 'ultimatejz/VRP-DQN-final'

env_params:
    map_dirc: './config/3s_no_flow'
    n_bus: 1
    bus_capacity: 12
    bus_stop_time: 1
    skip_station: False
    frame_rate: 3
    total_time: 1

reward_params:
    queue_reward: 0
    wait_reward: 0
    opr_reward: -100
    efficiency_reward: 0
    time_penalty_power: 1
    invalid_route_reward: -100

agent_params:
    double_dqn: True
    batch_size: 32
    gamma: 0.99
    episodes: 1000
    loss: 'mse'
    fix_date: False
    replay_memory_cap: 100000
    replay_start: 0
    reward_verbose_freq: 200
    replay_freq: 1
    hist_len: 4
    target_update_freq: 1000
    epsilon:
        start: 0
        end: 0
        end_t: 1000
    optim_params:
        lr: 0.00002
        momentum: 0.95
        eps: 0.01
    network:
        l1w: 256
        l2w: 128
        l3w: 128
    save_dir: './model_log/'
    log_freq: 25
